## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [2]:
import numpy as np
np.linspace(-1.3, 2.5, num=64)

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [2]:
import numpy as np
n = 7
np.array([1, 2, 3]*n)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

3.	Создайте массив первых 10 нечетных целых чисел.

In [28]:
np.linspace(1, 20, 20)[0:19:2]


array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [43]:
a = np.zeros((10,10))
a[0] = 1
a[-1] = 1
a[:,0] = 1
a[:,-1] = 1
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [46]:
a = np.zeros((8,8), dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [17]:
import numpy as np
n = 5
def power(i, j):
  return i + j
a = np.fromfunction(power, (n, n))
a

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 5.],
       [2., 3., 4., 5., 6.],
       [3., 4., 5., 6., 7.],
       [4., 5., 6., 7., 8.]])

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [22]:
import numpy as np
a = np.random.randint(1,10,5)
b = np.random.randint(1,10,5)
m1 = np.random.randint(1, 10, size=(5, 5))
m2 = np.random.randint(1, 10, size=(5, 5))
res1 = np.dot(a, b)
res2 = np.dot(m1, b)
res3 = np.dot(m1, m2)
print('Вектор 1', a )
print('Вектор 2', b )
print('Массив 1\n', m1 )
print('Массив 2\n', m2 )
print('a*b', res1 )
print('a*m2\n', res2 )
print('m1*m2\n', res3 )

Вектор 1 [8 6 9 3 3]
Вектор 2 [7 6 2 6 8]
Массив 1
 [[7 8 5 6 3]
 [7 1 1 9 2]
 [8 5 1 3 2]
 [7 4 4 1 8]
 [3 5 5 7 4]]
Массив 2
 [[3 6 9 9 7]
 [6 6 9 5 7]
 [8 3 8 9 4]
 [2 8 2 5 7]
 [5 2 4 1 4]]
a*b 152
a*m2
 [167 127 122 151 135]
m1*m2
 [[136 159 199 181 179]
 [ 63 127 106 124 131]
 [ 78 109 139 123 124]
 [119 102 165 132 132]
 [113 127 142 136 141]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [21]:
a = np.linspace(0, 1.0, 21)
#print(a)
cosinus = np.cos(a)
sinus = np.sin(a)
print(list(cosinus)+list(sinus))


[1.0, 0.9987502603949663, 0.9950041652780258, 0.9887710779360422, 0.9800665778412416, 0.9689124217106447, 0.955336489125606, 0.9393727128473789, 0.9210609940028851, 0.9004471023526769, 0.8775825618903728, 0.8525245220595057, 0.8253356149096782, 0.7960837985490559, 0.7648421872844884, 0.7316888688738209, 0.6967067093471654, 0.6599831458849821, 0.6216099682706644, 0.5816830894638835, 0.5403023058681398, 0.0, 0.04997916927067833, 0.09983341664682815, 0.14943813247359924, 0.19866933079506122, 0.24740395925452294, 0.2955202066613396, 0.3428978074554514, 0.3894183423086505, 0.43496553411123023, 0.479425538604203, 0.5226872289306592, 0.5646424733950355, 0.6051864057360395, 0.6442176872376911, 0.6816387600233341, 0.7173560908995228, 0.7512804051402927, 0.7833269096274834, 0.8134155047893737, 0.8414709848078965]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [23]:
import numpy as np
A = np.random.rand(3,5)
print (A)

[[0.99439001 0.61882214 0.61997631 0.1493469  0.59856209]
 [0.07833066 0.59072266 0.70070312 0.04842809 0.15635454]
 [0.65246056 0.78340722 0.39788964 0.18612208 0.78754429]]


10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [24]:
sum = np.sum(A)
sum_col = np.sum(A, axis = 0)
sum_row = np.sum(A, axis = 1)
mean = np.mean(A, axis = 1)
variance = np.var(A, axis = 1)
std_deviation = np.std(A, axis = 1)
print(f'Сумма всех элементов: {sum}\nCумма внутри строк: {sum_row}\nСумма внутри столбцов: {sum_col}\n' \
      f'Средние значения: {mean}\nДисперсии: {variance}\nСтандартные отклонения: {std_deviation}')

Сумма всех элементов: 7.3630603144834605
Cумма внутри строк: [2.98109744 1.57453908 2.80742379]
Сумма внутри столбцов: [1.72518123 1.99295202 1.71856908 0.38389706 1.54246092]
Средние значения: [0.59621949 0.31490782 0.56148476]
Дисперсии: [0.07186313 0.07540624 0.05525792]
Стандартные отклонения: [0.26807299 0.27460196 0.23507003]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [26]:
for i in range(len(A)):
    A[i,:] -= A.mean(1)[i]
    A[i,:] /= A.std(1)[i]
A

array([[ 1.48530639,  0.08431527,  0.08862074, -1.66698106,  0.00873866],
       [-0.86152755,  1.00441689,  1.40492554, -0.9704218 , -0.57739308],
       [ 0.38701575,  0.94406957, -0.69594205, -1.59681216,  0.96166889]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [ ]:
A[A[:, 2].argsort()]

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [29]:
b = np.dot(np.transpose(A), A)
c = np.dot(A, np.transpose(A))
print(b)
print(c)

[[ 3.09814597 -0.37472901 -1.34809363 -2.25792396  0.88260063]
 [-0.37472901  1.90722971  0.7615853  -2.62276178  0.32867578]
 [-1.34809363  0.7615853   2.46600474 -0.39981074 -1.47968568]
 [-2.25792396 -2.62276178 -0.39981074  6.2703534  -0.98985692]
 [ 0.88260063  0.32867578 -1.47968568 -0.98985692  1.25826619]]
[[5.         0.54218998 3.26302087]
 [0.54218998 5.         0.6313883 ]
 [3.26302087 0.6313883  5.        ]]


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [30]:
np.sum(np.diagonal(b)) + np.sum(np.diagonal(c))

30.0

15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [31]:
#print(np.linalg.det(matrix)) A не квадратная, ошибка.
print(np.linalg.det(b))
print(np.linalg.det(c))
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(b))
print(np.linalg.matrix_rank(c))
w_b, v_b = np.linalg.eig(b)
w_c, v_b = np.linalg.eig(c)
print(w_b)
print(w_c)

0.0
70.53444384800845
3
3
3
[ 8.46197130e+00  4.80230897e+00  1.73571973e+00  2.53833415e-16
 -3.56376341e-16]
[8.4619713  1.73571973 4.80230897]


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [35]:
np.random.seed(1032201720)
np.random.randint(3)

1

In [36]:
print('Аналитическое решение интеграла 1: ', -2 * np.log(3) + 4 * np.log(2) - 1/2)
print('Аналитическое решение интеграла 9: ', np.pi/(2**(3/2)))

Аналитическое решение интеграла 1:  0.07536414490356158
Аналитическое решение интеграла 2:  1.1107207345395915


In [37]:
def func1(x):
    return (x+1)/(x**3-x**2)

def func2(x):
    return 1/np.sqrt(2+3*x-2*x**2, where = x!=2)

def solution(func,a, b, dx, method):
    n = int((b-a) / dx)
    xx = np.linspace(a, b, n)
    if method == 'rectangular':
        return dx*np.sum(func(xx))
    elif method == 'trapezoid':
        return dx/2*(func(xx[0]) + 2*np.sum(func(xx[1:-1])) + func(xx[-1]))
    elif method == 'simpson':
        return dx/3*(func(xx[0]) + 2*np.sum(func(xx[2:-1:2])) + 4*np.sum(func(xx[1:-2:2])) + func(xx[-1]))
    else:
        return 'Неверный метод'
    
print('Для интеграла 1:', solution(func1, -2, -1, 0.0001, 'rectangular'), 'Для интеграла 9:', solution(func2, 3/4, 2, 0.0001, 'rectangular') )
print('Для интеграла 1:', solution(func1, -2, -1, 0.0001, 'trapezoid'), 'Для интеграла 9:', solution(func2, 3/4, 2, 0.0001, 'trapezoid') )
print('Для интеграла 1:', solution(func1, -2, -1, 0.0001, 'simpson'), 'Для интеграла 9:', solution(func2, 3/4, 2, 0.0001, 'simpson') )

Для интеграла 1: 0.07536077471587936 Для интеграла 9: 1.1041419998928388
Для интеграла 1: 0.07535660804921268 Для интеграла 9: 1.1041172156215913
Для интеграла 1: 0.07535660765565484 Для интеграла 9: 1.1032101773676126
